// ddro_1w.v

// Generated using ACDS version 25.1.1 125

`timescale 1 ps / 1 ps
module ddro_1w (
		input  wire       ck,        //        ck.export,   In input and output paths, this clock feeds a packed register or DDIO. In bidirectional mode, this clock is the unique clock for the input and output paths if you turn off the Separate input/output Clocks parameter.
		input  wire [0:0] datain_h,  //  datain_h.fragment, TBD
		input  wire [0:0] datain_l,  //  datain_l.fragment, TBD
		output wire [0:0] dataout,   //   pad_out.export,   Output signal to the pad.Output signal to the pad.
		output wire [0:0] pad_out_b  // pad_out_b.export,   Negative node of the differential output signal to the pad. This port is available if you turn on the Use differential buffer option.
	);

	ddro_1w_altera_gpio_2300_revfsqy gpio_0 (
		.ck        (ck),        //   input,  width = 1,        ck.export
		.datain_h  (datain_h),  //   input,  width = 1,  datain_h.fragment
		.datain_l  (datain_l),  //   input,  width = 1,  datain_l.fragment
		.dataout   (dataout),   //  output,  width = 1,   pad_out.export
		.pad_out_b (pad_out_b)  //  output,  width = 1, pad_out_b.export
	);

endmodule
