// ring_buffer.v

// Generated using ACDS version 25.1.1 125

`timescale 1 ps / 1 ps
module ring_buffer (
		input  wire [31:0] data,      //      data.datain,    Data input of the memory.The data port is required for all RAM operation modes:SINGLE_PORT,DUAL_PORT,BIDIR_DUAL_PORT,QUAD_PORT
		output wire [31:0] q,         //         q.dataout,   Data output from the memory
		input  wire [9:0]  wraddress, // wraddress.wraddress, Write address input to the memory.
		input  wire [9:0]  rdaddress, // rdaddress.rdaddress, Read address input to the memory.
		input  wire        wren,      //      wren.wren,      Write enable input for address port.The wren signal is required for all RAM operation modes:SINGLE_PORT,DUAL_PORT,BIDIR_DUAL_PORT,QUAD_PORT
		input  wire        wrclock,   //   wrclock.clk
		input  wire        rdclock,   //   rdclock.clk
		input  wire        rden       //      rden.rden,      Read enable input for rdaddress port
	);

	ring_buffer_ram_2port_2060_r5ei7sq ram_2port_0 (
		.data      (data),      //   input,  width = 32,      data.datain
		.q         (q),         //  output,  width = 32,         q.dataout
		.wraddress (wraddress), //   input,  width = 10, wraddress.wraddress
		.rdaddress (rdaddress), //   input,  width = 10, rdaddress.rdaddress
		.wren      (wren),      //   input,   width = 1,      wren.wren
		.wrclock   (wrclock),   //   input,   width = 1,   wrclock.clk
		.rdclock   (rdclock),   //   input,   width = 1,   rdclock.clk
		.rden      (rden)       //   input,   width = 1,      rden.rden
	);

endmodule
