// reset_release.v

// Generated using ACDS version 25.1.1 125

`timescale 1 ps / 1 ps
module reset_release (
		output wire  ninit_done  // ninit_done.reset
	);

	intel_user_rst_clkgate intel_user_rst_clkgate_0 (
		.ninit_done (ninit_done)  //  output,  width = 1, ninit_done.reset
	);

endmodule
