// ddro_1w_altera_gpio_2300_revfsqy.v

// This file was auto-generated from altera_gpio_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 25.1.1 125

`timescale 1 ps / 1 ps
module ddro_1w_altera_gpio_2300_revfsqy (
		input  wire       ck,        //        ck.export,   In input and output paths, this clock feeds a packed register or DDIO. In bidirectional mode, this clock is the unique clock for the input and output paths if you turn off the Separate input/output Clocks parameter.
		input  wire [0:0] datain_h,  //  datain_h.fragment, TBD
		input  wire [0:0] datain_l,  //  datain_l.fragment, TBD
		output wire [0:0] dataout,   //   pad_out.export,   Output signal to the pad.Output signal to the pad.
		output wire [0:0] pad_out_b  // pad_out_b.export,   Negative node of the differential output signal to the pad. This port is available if you turn on the Use differential buffer option.
	);

	altera_gpio #(
		.SIZE                   (1),
		.PIN_TYPE               ("output"),
		.REGISTER_MODE          ("ddr"),
		.HALF_RATE              ("false"),
		.DDIO_WITH_DELAY        ("false"),
		.SEPARATE_I_O_CLOCKS    ("false"),
		.BUFFER_TYPE            ("differential"),
		.PSEUDO_DIFF            ("false"),
		.ARESET_MODE            ("none"),
		.SRESET_MODE            ("none"),
		.OPEN_DRAIN             ("false"),
		.BUS_HOLD               ("false"),
		.ENABLE_OE              ("false"),
		.ENABLE_CKE             ("false"),
		.ENABLE_TERM            ("false"),
		.DYNAMIC_PULL_UP_ENABLE ("false")
	) core (
		.ck                 (ck),                        //   input,  width = 1,        ck.export
		.din                ({datain_h[0],datain_l[0]}), //   input,  width = 2,  datain_h.fragment
		.pad_out            (dataout),                   //  output,  width = 1,   pad_out.export
		.pad_out_b          (pad_out_b),                 //  output,  width = 1, pad_out_b.export
		.cke                (1'b1),                      // (terminated),                       
		.ck_in              (1'b0),                      // (terminated),                       
		.ck_out             (1'b0),                      // (terminated),                       
		.puen               (1'b0),                      // (terminated),                       
		.dout               (),                          // (terminated),                       
		.oe                 (1'b0),                      // (terminated),                       
		.pad_io             (),                          // (terminated),                       
		.pad_io_b           (),                          // (terminated),                       
		.pad_in             (1'b0),                      // (terminated),                       
		.pad_in_b           (1'b0),                      // (terminated),                       
		.terminationcontrol (1'b0),                      // (terminated),                       
		.aclr               (1'b0),                      // (terminated),                       
		.aset               (1'b0),                      // (terminated),                       
		.sclr               (1'b0),                      // (terminated),                       
		.sset               (1'b0)                       // (terminated),                       
	);

endmodule
