// jesd204b_core.v

// Generated using ACDS version 25.1.1 125

`timescale 1 ps / 1 ps
module jesd204b_core (
		input  wire        pma_cu_clk,                     //                     pma_cu_clk.clk
		input  wire        pll_refclk,                     //                     pll_refclk.clk
		input  wire [1:0]  src_sss_grant,                  //                  src_sss_grant.src_rs_grant
		output wire [1:0]  src_sss_req,                    //                    src_sss_req.src_rs_req
		output wire        o_refclk_bus_out,               //               o_refclk_bus_out.refclk_bus_out
		input  wire        jesd204_rx_rst_n,               //               jesd204_rx_rst_n.reset_n
		input  wire [1:0]  rx_serial_data,                 //                 rx_serial_data.export
		input  wire [1:0]  rx_serial_data_n,               //               rx_serial_data_n.export
		output wire [1:0]  rxphy_clk,                      //                      rxphy_clk.export
		output wire        jesd204_rx_rst_ack_n,           //           jesd204_rx_rst_ack_n.export
		output wire [1:0]  rx_locked_to_data,              //              rx_locked_to_data.export
		output wire        jesd204_rx_out_of_reset,        //        jesd204_rx_out_of_reset.export
		input  wire        jesd204_rx_avs_chipselect,      //                 jesd204_rx_avs.chipselect
		input  wire [9:0]  jesd204_rx_avs_address,         //                               .address
		input  wire        jesd204_rx_avs_read,            //                               .read
		output wire [31:0] jesd204_rx_avs_readdata,        //                               .readdata
		output wire        jesd204_rx_avs_waitrequest,     //                               .waitrequest
		input  wire        jesd204_rx_avs_write,           //                               .write
		input  wire [31:0] jesd204_rx_avs_writedata,       //                               .writedata
		output wire        jesd204_rx_int,                 //                 jesd204_rx_int.irq
		output wire [63:0] jesd204_rx_link_data,           //                jesd204_rx_link.data
		output wire        jesd204_rx_link_valid,          //                               .valid
		input  wire        jesd204_rx_link_ready,          //                               .ready
		output wire        jesd204_rx_dev_sync_n,          //          jesd204_rx_dev_sync_n.export
		input  wire        jesd204_rx_sysref,              //              jesd204_rx_sysref.export
		output wire [3:0]  jesd204_rx_somf,                //                jesd204_rx_somf.export
		output wire        jesd204_rx_csr_hd,              //              jesd204_rx_csr_hd.export
		output wire [1:0]  jesd204_rx_csr_cs,              //              jesd204_rx_csr_cs.export
		output wire [4:0]  jesd204_rx_csr_l,               //               jesd204_rx_csr_l.export
		output wire [4:0]  jesd204_rx_csr_k,               //               jesd204_rx_csr_k.export
		output wire [4:0]  jesd204_rx_csr_n,               //               jesd204_rx_csr_n.export
		output wire [4:0]  jesd204_rx_csr_np,              //              jesd204_rx_csr_np.export
		output wire [4:0]  jesd204_rx_csr_s,               //               jesd204_rx_csr_s.export
		output wire [4:0]  jesd204_rx_csr_cf,              //              jesd204_rx_csr_cf.export
		output wire [7:0]  jesd204_rx_csr_f,               //               jesd204_rx_csr_f.export
		output wire [7:0]  jesd204_rx_csr_m,               //               jesd204_rx_csr_m.export
		input  wire        jesd204_rx_alldev_lane_aligned, // jesd204_rx_alldev_lane_aligned.export
		output wire        jesd204_rx_dev_lane_aligned,    //    jesd204_rx_dev_lane_aligned.export
		output wire [3:0]  jesd204_rx_sof,                 //                 jesd204_rx_sof.export
		input  wire        jesd204_rx_frame_error,         //         jesd204_rx_frame_error.export
		output wire [3:0]  csr_rx_testmode,                //                csr_rx_testmode.export
		input  wire [63:0] jesd204_rx_dlb_data,            //            jesd204_rx_dlb_data.export
		input  wire [1:0]  jesd204_rx_dlb_data_valid,      //      jesd204_rx_dlb_data_valid.export
		input  wire [7:0]  jesd204_rx_dlb_kchar_data,      //      jesd204_rx_dlb_kchar_data.export
		input  wire [7:0]  jesd204_rx_dlb_errdetect,       //       jesd204_rx_dlb_errdetect.export
		input  wire [7:0]  jesd204_rx_dlb_disperr,         //         jesd204_rx_dlb_disperr.export
		input  wire        jesd204_rx_avs_rst_n,           //           jesd204_rx_avs_rst_n.reset_n
		input  wire        jesd204_rx_avs_clk,             //             jesd204_rx_avs_clk.clk
		input  wire        rxlink_clk                      //                     rxlink_clk.clk,           Clock Input
	);

	jesd204b_core_intel_jesd204b_gts_400_4ahcqsa #(
		.DEVICE_FAMILY          ("Agilex 5"),
		.SUBCLASSV              (1),
		.clocking_mode          ("PMA"),
		.PCS_CONFIG             ("JESD_PCS_CFG2"),
		.SER_SIZE               (4),
		.PMA_WIDTH              (40),
		.FK                     (32),
		.L                      (2),
		.M                      (2),
		.F                      (1),
		.N                      (8),
		.N_PRIME                (8),
		.K                      (32),
		.S                      (1),
		.SCR                    (1),
		.CS                     (0),
		.CF                     (0),
		.HD                     (0),
		.ECC_EN                 (1),
		.ENABLE_PERFORMANCE     (1),
		.PHADJ                  (0),
		.ADJCNT                 (0),
		.ADJDIR                 (0),
		.TX_EFIFO_PIPE_EN       (0),
		.RX_EFIFO_PIPE_EN       (0),
		.DID                    (0),
		.BID                    (0),
		.JESDV                  (1),
		.OPTIMIZE               (0),
		.BIT_REVERSAL           (0),
		.BYTE_REVERSAL          (0),
		.RES1                   (0),
		.RES2                   (0),
		.LID0                   (0),
		.FCHK0                  (0),
		.LID1                   (1),
		.FCHK1                  (0),
		.LID2                   (2),
		.FCHK2                  (0),
		.LID3                   (3),
		.FCHK3                  (0),
		.LID4                   (4),
		.FCHK4                  (0),
		.LID5                   (5),
		.FCHK5                  (0),
		.LID6                   (6),
		.FCHK6                  (0),
		.LID7                   (7),
		.FCHK7                  (0),
		.ALIGNMENT_PATTERN      (658812),
		.PULSE_WIDTH            (5),
		.LS_FIFO_DEPTH          (16),
		.LS_FIFO_WIDTHU         (4),
		.AVST_WIDTH             (128),
		.RECONFIG_ADDRESS_WIDTH (19),
		.SUBCLASSV_2            (0),
		.PCS_CONFIG_2           ("JESD_PCS_CFG2"),
		.L_2                    (4),
		.M_2                    (8),
		.F_2                    (4),
		.N_2                    (16),
		.N_PRIME_2              (16),
		.K_2                    (16),
		.S_2                    (1),
		.SCR_2                  (1),
		.CS_2                   (0),
		.CF_2                   (0),
		.HD_2                   (0),
		.ECC_EN_2               (1),
		.PHADJ_2                (0),
		.ADJCNT_2               (0),
		.ADJDIR_2               (0),
		.DID_2                  (0),
		.BID_2                  (0),
		.JESDV_2                (1),
		.OPTIMIZE_2             (0),
		.RES1_2                 (0),
		.RES2_2                 (0),
		.LID0_2                 (0),
		.FCHK0_2                (0),
		.LID1_2                 (1),
		.FCHK1_2                (0),
		.LID2_2                 (2),
		.FCHK2_2                (0),
		.LID3_2                 (3),
		.FCHK3_2                (0),
		.LID4_2                 (4),
		.FCHK4_2                (0),
		.LID5_2                 (5),
		.FCHK5_2                (0),
		.LID6_2                 (6),
		.FCHK6_2                (0),
		.LID7_2                 (7),
		.FCHK7_2                (0),
		.LS_FIFO_DEPTH_2        (256)
	) intel_jesd204b_gts_0 (
		.pma_cu_clk                     (pma_cu_clk),                     //   input,   width = 1,                     pma_cu_clk.clk
		.pll_refclk                     (pll_refclk),                     //   input,   width = 1,                     pll_refclk.clk
		.src_sss_grant                  (src_sss_grant),                  //   input,   width = 2,                  src_sss_grant.src_rs_grant
		.src_sss_req                    (src_sss_req),                    //  output,   width = 2,                    src_sss_req.src_rs_req
		.o_refclk_bus_out               (o_refclk_bus_out),               //  output,   width = 1,               o_refclk_bus_out.refclk_bus_out
		.jesd204_rx_rst_n               (jesd204_rx_rst_n),               //   input,   width = 1,               jesd204_rx_rst_n.reset_n
		.rx_serial_data                 (rx_serial_data),                 //   input,   width = 2,                 rx_serial_data.export
		.rx_serial_data_n               (rx_serial_data_n),               //   input,   width = 2,               rx_serial_data_n.export
		.rxphy_clk                      (rxphy_clk),                      //  output,   width = 2,                      rxphy_clk.export
		.jesd204_rx_rst_ack_n           (jesd204_rx_rst_ack_n),           //  output,   width = 1,           jesd204_rx_rst_ack_n.export
		.rx_locked_to_data              (rx_locked_to_data),              //  output,   width = 2,              rx_locked_to_data.export
		.jesd204_rx_out_of_reset        (jesd204_rx_out_of_reset),        //  output,   width = 1,        jesd204_rx_out_of_reset.export
		.jesd204_rx_avs_chipselect      (jesd204_rx_avs_chipselect),      //   input,   width = 1,                 jesd204_rx_avs.chipselect
		.jesd204_rx_avs_address         (jesd204_rx_avs_address),         //   input,  width = 10,                               .address
		.jesd204_rx_avs_read            (jesd204_rx_avs_read),            //   input,   width = 1,                               .read
		.jesd204_rx_avs_readdata        (jesd204_rx_avs_readdata),        //  output,  width = 32,                               .readdata
		.jesd204_rx_avs_waitrequest     (jesd204_rx_avs_waitrequest),     //  output,   width = 1,                               .waitrequest
		.jesd204_rx_avs_write           (jesd204_rx_avs_write),           //   input,   width = 1,                               .write
		.jesd204_rx_avs_writedata       (jesd204_rx_avs_writedata),       //   input,  width = 32,                               .writedata
		.jesd204_rx_int                 (jesd204_rx_int),                 //  output,   width = 1,                 jesd204_rx_int.irq
		.jesd204_rx_link_data           (jesd204_rx_link_data),           //  output,  width = 64,                jesd204_rx_link.data
		.jesd204_rx_link_valid          (jesd204_rx_link_valid),          //  output,   width = 1,                               .valid
		.jesd204_rx_link_ready          (jesd204_rx_link_ready),          //   input,   width = 1,                               .ready
		.jesd204_rx_dev_sync_n          (jesd204_rx_dev_sync_n),          //  output,   width = 1,          jesd204_rx_dev_sync_n.export
		.jesd204_rx_sysref              (jesd204_rx_sysref),              //   input,   width = 1,              jesd204_rx_sysref.export
		.jesd204_rx_somf                (jesd204_rx_somf),                //  output,   width = 4,                jesd204_rx_somf.export
		.jesd204_rx_csr_hd              (jesd204_rx_csr_hd),              //  output,   width = 1,              jesd204_rx_csr_hd.export
		.jesd204_rx_csr_cs              (jesd204_rx_csr_cs),              //  output,   width = 2,              jesd204_rx_csr_cs.export
		.jesd204_rx_csr_l               (jesd204_rx_csr_l),               //  output,   width = 5,               jesd204_rx_csr_l.export
		.jesd204_rx_csr_k               (jesd204_rx_csr_k),               //  output,   width = 5,               jesd204_rx_csr_k.export
		.jesd204_rx_csr_n               (jesd204_rx_csr_n),               //  output,   width = 5,               jesd204_rx_csr_n.export
		.jesd204_rx_csr_np              (jesd204_rx_csr_np),              //  output,   width = 5,              jesd204_rx_csr_np.export
		.jesd204_rx_csr_s               (jesd204_rx_csr_s),               //  output,   width = 5,               jesd204_rx_csr_s.export
		.jesd204_rx_csr_cf              (jesd204_rx_csr_cf),              //  output,   width = 5,              jesd204_rx_csr_cf.export
		.jesd204_rx_csr_f               (jesd204_rx_csr_f),               //  output,   width = 8,               jesd204_rx_csr_f.export
		.jesd204_rx_csr_m               (jesd204_rx_csr_m),               //  output,   width = 8,               jesd204_rx_csr_m.export
		.jesd204_rx_alldev_lane_aligned (jesd204_rx_alldev_lane_aligned), //   input,   width = 1, jesd204_rx_alldev_lane_aligned.export
		.jesd204_rx_dev_lane_aligned    (jesd204_rx_dev_lane_aligned),    //  output,   width = 1,    jesd204_rx_dev_lane_aligned.export
		.jesd204_rx_sof                 (jesd204_rx_sof),                 //  output,   width = 4,                 jesd204_rx_sof.export
		.jesd204_rx_frame_error         (jesd204_rx_frame_error),         //   input,   width = 1,         jesd204_rx_frame_error.export
		.csr_rx_testmode                (csr_rx_testmode),                //  output,   width = 4,                csr_rx_testmode.export
		.jesd204_rx_dlb_data            (jesd204_rx_dlb_data),            //   input,  width = 64,            jesd204_rx_dlb_data.export
		.jesd204_rx_dlb_data_valid      (jesd204_rx_dlb_data_valid),      //   input,   width = 2,      jesd204_rx_dlb_data_valid.export
		.jesd204_rx_dlb_kchar_data      (jesd204_rx_dlb_kchar_data),      //   input,   width = 8,      jesd204_rx_dlb_kchar_data.export
		.jesd204_rx_dlb_errdetect       (jesd204_rx_dlb_errdetect),       //   input,   width = 8,       jesd204_rx_dlb_errdetect.export
		.jesd204_rx_dlb_disperr         (jesd204_rx_dlb_disperr),         //   input,   width = 8,         jesd204_rx_dlb_disperr.export
		.jesd204_rx_avs_rst_n           (jesd204_rx_avs_rst_n),           //   input,   width = 1,           jesd204_rx_avs_rst_n.reset_n
		.jesd204_rx_avs_clk             (jesd204_rx_avs_clk),             //   input,   width = 1,             jesd204_rx_avs_clk.clk
		.rxlink_clk                     (rxlink_clk)                      //   input,   width = 1,                     rxlink_clk.clk
	);

endmodule
