// niosv_pd.v

// Generated using ACDS version 25.1.1 125

`timescale 1 ps / 1 ps
module niosv_pd (
		output wire [14:0] avalon_spi_slave_address,          //       avalon_spi_slave.address
		output wire        avalon_spi_slave_chipselect,       //                       .chipselect
		input  wire        avalon_spi_slave_waitrequest,      //                       .waitrequest
		output wire        avalon_spi_slave_write,            //                       .write
		output wire [31:0] avalon_spi_slave_writedata,        //                       .writedata
		output wire        avalon_spi_slave_read,             //                       .read
		input  wire [31:0] avalon_spi_slave_readdata,         //                       .readdata
		input  wire        avalon_spi_slave_readdatavalid,    //                       .readdatavalid
		output wire        avalon_spi_slave_reset_reset,      // avalon_spi_slave_reset.reset
		input  wire        avalon_spi_slave_irq_irq,          //   avalon_spi_slave_irq.irq
		output wire [7:0]  i2c_master_0_avl_mm_address,       //    i2c_master_0_avl_mm.address
		output wire        i2c_master_0_avl_mm_chipselect,    //                       .chipselect
		output wire        i2c_master_0_avl_mm_write,         //                       .write
		input  wire        i2c_master_0_avl_mm_waitrequest,   //                       .waitrequest
		output wire [31:0] i2c_master_0_avl_mm_writedata,     //                       .writedata
		output wire        i2c_master_0_avl_mm_read,          //                       .read
		input  wire [31:0] i2c_master_0_avl_mm_readdata,      //                       .readdata
		input  wire        i2c_master_0_avl_mm_readdatavalid, //                       .readdatavalid
		output wire        i2c_master_0_avl_reset_reset,      // i2c_master_0_avl_reset.reset
		input  wire [31:0] avl_mst_sbc_address,               //            avl_mst_sbc.address
		output wire        avl_mst_sbc_waitrequest,           //                       .waitrequest
		input  wire        avl_mst_sbc_write,                 //                       .write
		input  wire [31:0] avl_mst_sbc_writedata,             //                       .writedata
		input  wire        avl_mst_sbc_read,                  //                       .read
		output wire [31:0] avl_mst_sbc_readdata,              //                       .readdata
		output wire        avl_mst_sbc_readdatavalid,         //                       .readdatavalid
		output wire        avl_mst_sb_reset_reset,            //       avl_mst_sb_reset.reset
		output wire [7:0]  spi_master_0_avl_mm_address,       //    spi_master_0_avl_mm.address
		output wire        spi_master_0_avl_mm_chipselect,    //                       .chipselect
		output wire        spi_master_0_avl_mm_write,         //                       .write
		input  wire        spi_master_0_avl_mm_waitrequest,   //                       .waitrequest
		output wire [31:0] spi_master_0_avl_mm_writedata,     //                       .writedata
		output wire        spi_master_0_avl_mm_read,          //                       .read
		input  wire [31:0] spi_master_0_avl_mm_readdata,      //                       .readdata
		input  wire        spi_master_0_avl_mm_readdatavalid, //                       .readdatavalid
		output wire        spi_master_0_avl_reset_reset,      // spi_master_0_avl_reset.reset
		input  wire        clk_clk,                           //                    clk.clk
		output wire [9:0]  jesd_low_slave_address,            //         jesd_low_slave.address
		output wire        jesd_low_slave_chipselect,         //                       .chipselect
		output wire        jesd_low_slave_read,               //                       .read
		input  wire [31:0] jesd_low_slave_readdata,           //                       .readdata
		input  wire        jesd_low_slave_waitrequest,        //                       .waitrequest
		output wire        jesd_low_slave_write,              //                       .write
		output wire [31:0] jesd_low_slave_writedata,          //                       .writedata
		output wire        jesd_low_slave_reset_reset_n,      //   jesd_low_slave_reset.reset_n
		output wire [9:0]  jesd_high_slave_address,           //        jesd_high_slave.address
		output wire        jesd_high_slave_chipselect,        //                       .chipselect
		output wire        jesd_high_slave_read,              //                       .read
		input  wire [31:0] jesd_high_slave_readdata,          //                       .readdata
		input  wire        jesd_high_slave_waitrequest,       //                       .waitrequest
		output wire        jesd_high_slave_write,             //                       .write
		output wire [31:0] jesd_high_slave_writedata,         //                       .writedata
		output wire        jesd_high_slave_reset_reset_n,     //  jesd_high_slave_reset.reset_n
		input  wire        pd_debug_uart_rxd,                 //          pd_debug_uart.rxd
		output wire        pd_debug_uart_txd,                 //                       .txd
		input  wire        reset_reset_n,                     //                  reset.reset_n
		input  wire [31:0] ser_debug_master_address,          //       ser_debug_master.address
		output wire        ser_debug_master_waitrequest,      //                       .waitrequest
		input  wire        ser_debug_master_write,            //                       .write
		input  wire [31:0] ser_debug_master_writedata,        //                       .writedata
		input  wire        ser_debug_master_read,             //                       .read
		output wire [31:0] ser_debug_master_readdata,         //                       .readdata
		output wire        ser_debug_master_readdatavalid,    //                       .readdatavalid
		input  wire [3:0]  ser_debug_master_byteenable,       //                       .byteenable
		output wire        ser_debug_master_reset_reset       // ser_debug_master_reset.reset
	);

	wire         clock_in_out_clk_clk;                                                // clock_in:out_clk -> [avalon_spi_slave_0:clk, avl_i2c_master_0:clock_sink_clk, avl_mst_sbc:clock_sink_clk, avl_spi_master_0:clock_sink_clk, data_memory_1:clk, intel_mailbox_client_0:in_clk_clk, jesd_12_chan_interface_0:clk, jesd_12_chan_interface_1:clk, mm_interconnect_0:clock_in_out_clk_clk, pd_uart:clk, program_memory_0:clk, reset_in:clk, rst_controller:clk, rst_controller_001:clk, tectonics_ser_debug_0:clock_sink_clk, timer_0:clk]
	wire         tectonics_ser_debug_0_avalon_master_waitrequest;                     // mm_interconnect_0:tectonics_ser_debug_0_avalon_master_waitrequest -> tectonics_ser_debug_0:avalon_master_waitrequest
	wire  [31:0] tectonics_ser_debug_0_avalon_master_readdata;                        // mm_interconnect_0:tectonics_ser_debug_0_avalon_master_readdata -> tectonics_ser_debug_0:avalon_master_readdata
	wire  [31:0] tectonics_ser_debug_0_avalon_master_address;                         // tectonics_ser_debug_0:avalon_master_address -> mm_interconnect_0:tectonics_ser_debug_0_avalon_master_address
	wire         tectonics_ser_debug_0_avalon_master_read;                            // tectonics_ser_debug_0:avalon_master_read -> mm_interconnect_0:tectonics_ser_debug_0_avalon_master_read
	wire   [3:0] tectonics_ser_debug_0_avalon_master_byteenable;                      // tectonics_ser_debug_0:avalon_master_byteenable -> mm_interconnect_0:tectonics_ser_debug_0_avalon_master_byteenable
	wire         tectonics_ser_debug_0_avalon_master_readdatavalid;                   // mm_interconnect_0:tectonics_ser_debug_0_avalon_master_readdatavalid -> tectonics_ser_debug_0:avalon_master_readdatavalid
	wire         tectonics_ser_debug_0_avalon_master_write;                           // tectonics_ser_debug_0:avalon_master_write -> mm_interconnect_0:tectonics_ser_debug_0_avalon_master_write
	wire  [31:0] tectonics_ser_debug_0_avalon_master_writedata;                       // tectonics_ser_debug_0:avalon_master_writedata -> mm_interconnect_0:tectonics_ser_debug_0_avalon_master_writedata
	wire         avl_mst_sbc_avalon_master_waitrequest;                               // mm_interconnect_0:avl_mst_sbc_avalon_master_waitrequest -> avl_mst_sbc:avalon_master_waitrequest
	wire  [31:0] avl_mst_sbc_avalon_master_readdata;                                  // mm_interconnect_0:avl_mst_sbc_avalon_master_readdata -> avl_mst_sbc:avalon_master_readdata
	wire  [31:0] avl_mst_sbc_avalon_master_address;                                   // avl_mst_sbc:avalon_master_address -> mm_interconnect_0:avl_mst_sbc_avalon_master_address
	wire         avl_mst_sbc_avalon_master_read;                                      // avl_mst_sbc:avalon_master_read -> mm_interconnect_0:avl_mst_sbc_avalon_master_read
	wire         avl_mst_sbc_avalon_master_readdatavalid;                             // mm_interconnect_0:avl_mst_sbc_avalon_master_readdatavalid -> avl_mst_sbc:avalon_master_readdatavalid
	wire         avl_mst_sbc_avalon_master_write;                                     // avl_mst_sbc:avalon_master_write -> mm_interconnect_0:avl_mst_sbc_avalon_master_write
	wire  [31:0] avl_mst_sbc_avalon_master_writedata;                                 // avl_mst_sbc:avalon_master_writedata -> mm_interconnect_0:avl_mst_sbc_avalon_master_writedata
	wire         mm_interconnect_0_jesd_12_chan_interface_1_avalon_slave_chipselect;  // mm_interconnect_0:jesd_12_chan_interface_1_avalon_slave_chipselect -> jesd_12_chan_interface_1:chipselect
	wire  [31:0] mm_interconnect_0_jesd_12_chan_interface_1_avalon_slave_readdata;    // jesd_12_chan_interface_1:readdata -> mm_interconnect_0:jesd_12_chan_interface_1_avalon_slave_readdata
	wire         mm_interconnect_0_jesd_12_chan_interface_1_avalon_slave_waitrequest; // jesd_12_chan_interface_1:waitrequest -> mm_interconnect_0:jesd_12_chan_interface_1_avalon_slave_waitrequest
	wire   [9:0] mm_interconnect_0_jesd_12_chan_interface_1_avalon_slave_address;     // mm_interconnect_0:jesd_12_chan_interface_1_avalon_slave_address -> jesd_12_chan_interface_1:address
	wire         mm_interconnect_0_jesd_12_chan_interface_1_avalon_slave_read;        // mm_interconnect_0:jesd_12_chan_interface_1_avalon_slave_read -> jesd_12_chan_interface_1:read
	wire         mm_interconnect_0_jesd_12_chan_interface_1_avalon_slave_write;       // mm_interconnect_0:jesd_12_chan_interface_1_avalon_slave_write -> jesd_12_chan_interface_1:write
	wire  [31:0] mm_interconnect_0_jesd_12_chan_interface_1_avalon_slave_writedata;   // mm_interconnect_0:jesd_12_chan_interface_1_avalon_slave_writedata -> jesd_12_chan_interface_1:writedata
	wire         mm_interconnect_0_jesd_12_chan_interface_0_avalon_slave_chipselect;  // mm_interconnect_0:jesd_12_chan_interface_0_avalon_slave_chipselect -> jesd_12_chan_interface_0:chipselect
	wire  [31:0] mm_interconnect_0_jesd_12_chan_interface_0_avalon_slave_readdata;    // jesd_12_chan_interface_0:readdata -> mm_interconnect_0:jesd_12_chan_interface_0_avalon_slave_readdata
	wire         mm_interconnect_0_jesd_12_chan_interface_0_avalon_slave_waitrequest; // jesd_12_chan_interface_0:waitrequest -> mm_interconnect_0:jesd_12_chan_interface_0_avalon_slave_waitrequest
	wire   [9:0] mm_interconnect_0_jesd_12_chan_interface_0_avalon_slave_address;     // mm_interconnect_0:jesd_12_chan_interface_0_avalon_slave_address -> jesd_12_chan_interface_0:address
	wire         mm_interconnect_0_jesd_12_chan_interface_0_avalon_slave_read;        // mm_interconnect_0:jesd_12_chan_interface_0_avalon_slave_read -> jesd_12_chan_interface_0:read
	wire         mm_interconnect_0_jesd_12_chan_interface_0_avalon_slave_write;       // mm_interconnect_0:jesd_12_chan_interface_0_avalon_slave_write -> jesd_12_chan_interface_0:write
	wire  [31:0] mm_interconnect_0_jesd_12_chan_interface_0_avalon_slave_writedata;   // mm_interconnect_0:jesd_12_chan_interface_0_avalon_slave_writedata -> jesd_12_chan_interface_0:writedata
	wire         mm_interconnect_0_avalon_spi_slave_0_avalon_slave_chipselect;        // mm_interconnect_0:avalon_spi_slave_0_avalon_slave_chipselect -> avalon_spi_slave_0:chipselect
	wire  [31:0] mm_interconnect_0_avalon_spi_slave_0_avalon_slave_readdata;          // avalon_spi_slave_0:readdata -> mm_interconnect_0:avalon_spi_slave_0_avalon_slave_readdata
	wire         mm_interconnect_0_avalon_spi_slave_0_avalon_slave_waitrequest;       // avalon_spi_slave_0:waitrequest -> mm_interconnect_0:avalon_spi_slave_0_avalon_slave_waitrequest
	wire  [14:0] mm_interconnect_0_avalon_spi_slave_0_avalon_slave_address;           // mm_interconnect_0:avalon_spi_slave_0_avalon_slave_address -> avalon_spi_slave_0:address
	wire         mm_interconnect_0_avalon_spi_slave_0_avalon_slave_read;              // mm_interconnect_0:avalon_spi_slave_0_avalon_slave_read -> avalon_spi_slave_0:read
	wire         mm_interconnect_0_avalon_spi_slave_0_avalon_slave_readdatavalid;     // avalon_spi_slave_0:readdatavalid -> mm_interconnect_0:avalon_spi_slave_0_avalon_slave_readdatavalid
	wire         mm_interconnect_0_avalon_spi_slave_0_avalon_slave_write;             // mm_interconnect_0:avalon_spi_slave_0_avalon_slave_write -> avalon_spi_slave_0:write
	wire  [31:0] mm_interconnect_0_avalon_spi_slave_0_avalon_slave_writedata;         // mm_interconnect_0:avalon_spi_slave_0_avalon_slave_writedata -> avalon_spi_slave_0:writedata
	wire         mm_interconnect_0_avl_spi_master_0_avalon_slave_chipselect;          // mm_interconnect_0:avl_spi_master_0_avalon_slave_chipselect -> avl_spi_master_0:avalon_slave_chipselect
	wire  [31:0] mm_interconnect_0_avl_spi_master_0_avalon_slave_readdata;            // avl_spi_master_0:avalon_slave_readdata -> mm_interconnect_0:avl_spi_master_0_avalon_slave_readdata
	wire         mm_interconnect_0_avl_spi_master_0_avalon_slave_waitrequest;         // avl_spi_master_0:avalon_slave_waitrequest -> mm_interconnect_0:avl_spi_master_0_avalon_slave_waitrequest
	wire   [7:0] mm_interconnect_0_avl_spi_master_0_avalon_slave_address;             // mm_interconnect_0:avl_spi_master_0_avalon_slave_address -> avl_spi_master_0:avalon_slave_address
	wire         mm_interconnect_0_avl_spi_master_0_avalon_slave_read;                // mm_interconnect_0:avl_spi_master_0_avalon_slave_read -> avl_spi_master_0:avalon_slave_read
	wire         mm_interconnect_0_avl_spi_master_0_avalon_slave_readdatavalid;       // avl_spi_master_0:avalon_slave_readdatavalid -> mm_interconnect_0:avl_spi_master_0_avalon_slave_readdatavalid
	wire         mm_interconnect_0_avl_spi_master_0_avalon_slave_write;               // mm_interconnect_0:avl_spi_master_0_avalon_slave_write -> avl_spi_master_0:avalon_slave_write
	wire  [31:0] mm_interconnect_0_avl_spi_master_0_avalon_slave_writedata;           // mm_interconnect_0:avl_spi_master_0_avalon_slave_writedata -> avl_spi_master_0:avalon_slave_writedata
	wire         mm_interconnect_0_avl_i2c_master_0_avalon_slave_chipselect;          // mm_interconnect_0:avl_i2c_master_0_avalon_slave_chipselect -> avl_i2c_master_0:avalon_slave_chipselect
	wire  [31:0] mm_interconnect_0_avl_i2c_master_0_avalon_slave_readdata;            // avl_i2c_master_0:avalon_slave_readdata -> mm_interconnect_0:avl_i2c_master_0_avalon_slave_readdata
	wire         mm_interconnect_0_avl_i2c_master_0_avalon_slave_waitrequest;         // avl_i2c_master_0:avalon_slave_waitrequest -> mm_interconnect_0:avl_i2c_master_0_avalon_slave_waitrequest
	wire   [7:0] mm_interconnect_0_avl_i2c_master_0_avalon_slave_address;             // mm_interconnect_0:avl_i2c_master_0_avalon_slave_address -> avl_i2c_master_0:avalon_slave_address
	wire         mm_interconnect_0_avl_i2c_master_0_avalon_slave_read;                // mm_interconnect_0:avl_i2c_master_0_avalon_slave_read -> avl_i2c_master_0:avalon_slave_read
	wire         mm_interconnect_0_avl_i2c_master_0_avalon_slave_readdatavalid;       // avl_i2c_master_0:avalon_slave_readdatavalid -> mm_interconnect_0:avl_i2c_master_0_avalon_slave_readdatavalid
	wire         mm_interconnect_0_avl_i2c_master_0_avalon_slave_write;               // mm_interconnect_0:avl_i2c_master_0_avalon_slave_write -> avl_i2c_master_0:avalon_slave_write
	wire  [31:0] mm_interconnect_0_avl_i2c_master_0_avalon_slave_writedata;           // mm_interconnect_0:avl_i2c_master_0_avalon_slave_writedata -> avl_i2c_master_0:avalon_slave_writedata
	wire  [31:0] mm_interconnect_0_intel_mailbox_client_0_avmm_readdata;              // intel_mailbox_client_0:avmm_readdata -> mm_interconnect_0:intel_mailbox_client_0_avmm_readdata
	wire         mm_interconnect_0_intel_mailbox_client_0_avmm_waitrequest;           // intel_mailbox_client_0:avmm_waitrequest -> mm_interconnect_0:intel_mailbox_client_0_avmm_waitrequest
	wire   [3:0] mm_interconnect_0_intel_mailbox_client_0_avmm_address;               // mm_interconnect_0:intel_mailbox_client_0_avmm_address -> intel_mailbox_client_0:avmm_address
	wire         mm_interconnect_0_intel_mailbox_client_0_avmm_read;                  // mm_interconnect_0:intel_mailbox_client_0_avmm_read -> intel_mailbox_client_0:avmm_read
	wire         mm_interconnect_0_intel_mailbox_client_0_avmm_readdatavalid;         // intel_mailbox_client_0:avmm_readdatavalid -> mm_interconnect_0:intel_mailbox_client_0_avmm_readdatavalid
	wire         mm_interconnect_0_intel_mailbox_client_0_avmm_write;                 // mm_interconnect_0:intel_mailbox_client_0_avmm_write -> intel_mailbox_client_0:avmm_write
	wire  [31:0] mm_interconnect_0_intel_mailbox_client_0_avmm_writedata;             // mm_interconnect_0:intel_mailbox_client_0_avmm_writedata -> intel_mailbox_client_0:avmm_writedata
	wire  [15:0] mm_interconnect_0_pd_uart_s1_readdata;                               // pd_uart:readdata -> mm_interconnect_0:pd_uart_s1_readdata
	wire   [2:0] mm_interconnect_0_pd_uart_s1_address;                                // mm_interconnect_0:pd_uart_s1_address -> pd_uart:address
	wire         mm_interconnect_0_pd_uart_s1_read;                                   // mm_interconnect_0:pd_uart_s1_read -> pd_uart:read
	wire         mm_interconnect_0_pd_uart_s1_write;                                  // mm_interconnect_0:pd_uart_s1_write -> pd_uart:write
	wire  [15:0] mm_interconnect_0_pd_uart_s1_writedata;                              // mm_interconnect_0:pd_uart_s1_writedata -> pd_uart:writedata
	wire         mm_interconnect_0_timer_0_s1_chipselect;                             // mm_interconnect_0:timer_0_s1_chipselect -> timer_0:chipselect
	wire  [15:0] mm_interconnect_0_timer_0_s1_readdata;                               // timer_0:readdata -> mm_interconnect_0:timer_0_s1_readdata
	wire   [2:0] mm_interconnect_0_timer_0_s1_address;                                // mm_interconnect_0:timer_0_s1_address -> timer_0:address
	wire         mm_interconnect_0_timer_0_s1_write;                                  // mm_interconnect_0:timer_0_s1_write -> timer_0:write_n
	wire  [15:0] mm_interconnect_0_timer_0_s1_writedata;                              // mm_interconnect_0:timer_0_s1_writedata -> timer_0:writedata
	wire  [31:0] mm_interconnect_0_data_memory_1_s1_readdata;                         // data_memory_1:readdata -> mm_interconnect_0:data_memory_1_s1_readdata
	wire  [14:0] mm_interconnect_0_data_memory_1_s1_address;                          // mm_interconnect_0:data_memory_1_s1_address -> data_memory_1:address
	wire         mm_interconnect_0_data_memory_1_s1_read;                             // mm_interconnect_0:data_memory_1_s1_read -> data_memory_1:read
	wire   [3:0] mm_interconnect_0_data_memory_1_s1_byteenable;                       // mm_interconnect_0:data_memory_1_s1_byteenable -> data_memory_1:byteenable
	wire         mm_interconnect_0_data_memory_1_s1_write;                            // mm_interconnect_0:data_memory_1_s1_write -> data_memory_1:write
	wire  [31:0] mm_interconnect_0_data_memory_1_s1_writedata;                        // mm_interconnect_0:data_memory_1_s1_writedata -> data_memory_1:writedata
	wire  [31:0] mm_interconnect_0_program_memory_0_s1_readdata;                      // program_memory_0:readdata -> mm_interconnect_0:program_memory_0_s1_readdata
	wire  [14:0] mm_interconnect_0_program_memory_0_s1_address;                       // mm_interconnect_0:program_memory_0_s1_address -> program_memory_0:address
	wire         mm_interconnect_0_program_memory_0_s1_read;                          // mm_interconnect_0:program_memory_0_s1_read -> program_memory_0:read
	wire   [3:0] mm_interconnect_0_program_memory_0_s1_byteenable;                    // mm_interconnect_0:program_memory_0_s1_byteenable -> program_memory_0:byteenable
	wire         mm_interconnect_0_program_memory_0_s1_write;                         // mm_interconnect_0:program_memory_0_s1_write -> program_memory_0:write
	wire  [31:0] mm_interconnect_0_program_memory_0_s1_writedata;                     // mm_interconnect_0:program_memory_0_s1_writedata -> program_memory_0:writedata
	wire         rst_controller_reset_out_reset;                                      // rst_controller:reset_out -> [avalon_spi_slave_0:reset, avl_i2c_master_0:reset_sink_reset, avl_mst_sbc:reset_sink_reset, avl_spi_master_0:reset_sink_reset, data_memory_1:reset, jesd_12_chan_interface_0:reset, jesd_12_chan_interface_1:reset, pd_uart:reset_n, program_memory_0:reset, rst_translator:in_reset, tectonics_ser_debug_0:reset_sink_reset, timer_0:reset_n]
	wire         rst_controller_reset_out_reset_req;                                  // rst_controller:reset_req -> [data_memory_1:reset_req, program_memory_0:reset_req, rst_translator:reset_req_in]
	wire         reset_in_out_reset_reset;                                            // reset_in:out_reset_n -> [rst_controller:reset_in0, rst_controller_001:reset_in0]
	wire         rst_controller_001_reset_out_reset;                                  // rst_controller_001:reset_out -> [intel_mailbox_client_0:in_reset_reset, mm_interconnect_0:intel_mailbox_client_0_in_reset_reset_bridge_in_reset_reset, mm_interconnect_0:tectonics_ser_debug_0_reset_sink_reset_bridge_in_reset_reset]

	niosv_pd_avalon_spi_slave_0 avalon_spi_slave_0 (
		.address                    (mm_interconnect_0_avalon_spi_slave_0_avalon_slave_address),       //   input,  width = 15,      avalon_slave.address
		.chipselect                 (mm_interconnect_0_avalon_spi_slave_0_avalon_slave_chipselect),    //   input,   width = 1,                  .chipselect
		.waitrequest                (mm_interconnect_0_avalon_spi_slave_0_avalon_slave_waitrequest),   //  output,   width = 1,                  .waitrequest
		.write                      (mm_interconnect_0_avalon_spi_slave_0_avalon_slave_write),         //   input,   width = 1,                  .write
		.writedata                  (mm_interconnect_0_avalon_spi_slave_0_avalon_slave_writedata),     //   input,  width = 32,                  .writedata
		.read                       (mm_interconnect_0_avalon_spi_slave_0_avalon_slave_read),          //   input,   width = 1,                  .read
		.readdata                   (mm_interconnect_0_avalon_spi_slave_0_avalon_slave_readdata),      //  output,  width = 32,                  .readdata
		.readdatavalid              (mm_interconnect_0_avalon_spi_slave_0_avalon_slave_readdatavalid), //  output,   width = 1,                  .readdatavalid
		.clk                        (clock_in_out_clk_clk),                                            //   input,   width = 1,        clock_sink.clk
		.reset                      (rst_controller_reset_out_reset),                                  //   input,   width = 1,        reset_sink.reset
		.irq                        (),                                                                //  output,   width = 1,  interrupt_sender.irq
		.avalon_slave_address       (avalon_spi_slave_address),                                        //  output,  width = 15,     avalon_slave1.address
		.avalon_slave_chipselect    (avalon_spi_slave_chipselect),                                     //  output,   width = 1,                  .chipselect
		.avalon_slave_waitrequest   (avalon_spi_slave_waitrequest),                                    //   input,   width = 1,                  .waitrequest
		.avalon_slave_write         (avalon_spi_slave_write),                                          //  output,   width = 1,                  .write
		.avalon_slave_writedata     (avalon_spi_slave_writedata),                                      //  output,  width = 32,                  .writedata
		.avalon_slave_read          (avalon_spi_slave_read),                                           //  output,   width = 1,                  .read
		.avalon_slave_readdata      (avalon_spi_slave_readdata),                                       //   input,  width = 32,                  .readdata
		.avalon_slave_readdatavalid (avalon_spi_slave_readdatavalid),                                  //   input,   width = 1,                  .readdatavalid
		.reset_sink_reset           (avalon_spi_slave_reset_reset),                                    //  output,   width = 1,       reset_sink1.reset
		.interrupt_sender_irq       (avalon_spi_slave_irq_irq)                                         //   input,   width = 1, interrupt_sender1.irq
	);

	niosv_pd_avl_i2c_master_0 avl_i2c_master_0 (
		.clock_sink_clk              (clock_in_out_clk_clk),                                          //   input,   width = 1,    clock_sink.clk
		.avalon_slave_address        (mm_interconnect_0_avl_i2c_master_0_avalon_slave_address),       //   input,   width = 8,  avalon_slave.address
		.avalon_slave_chipselect     (mm_interconnect_0_avl_i2c_master_0_avalon_slave_chipselect),    //   input,   width = 1,              .chipselect
		.avalon_slave_write          (mm_interconnect_0_avl_i2c_master_0_avalon_slave_write),         //   input,   width = 1,              .write
		.avalon_slave_waitrequest    (mm_interconnect_0_avl_i2c_master_0_avalon_slave_waitrequest),   //  output,   width = 1,              .waitrequest
		.avalon_slave_writedata      (mm_interconnect_0_avl_i2c_master_0_avalon_slave_writedata),     //   input,  width = 32,              .writedata
		.avalon_slave_read           (mm_interconnect_0_avl_i2c_master_0_avalon_slave_read),          //   input,   width = 1,              .read
		.avalon_slave_readdata       (mm_interconnect_0_avl_i2c_master_0_avalon_slave_readdata),      //  output,  width = 32,              .readdata
		.avalon_slave_readdatavalid  (mm_interconnect_0_avl_i2c_master_0_avalon_slave_readdatavalid), //  output,   width = 1,              .readdatavalid
		.reset_sink_reset            (rst_controller_reset_out_reset),                                //   input,   width = 1,    reset_sink.reset
		.avalon_slave_address1       (i2c_master_0_avl_mm_address),                                   //  output,   width = 8, avalon_slave1.address
		.avalon_slave_chipselect1    (i2c_master_0_avl_mm_chipselect),                                //  output,   width = 1,              .chipselect
		.avalon_slave_write1         (i2c_master_0_avl_mm_write),                                     //  output,   width = 1,              .write
		.avalon_slave_waitrequest1   (i2c_master_0_avl_mm_waitrequest),                               //   input,   width = 1,              .waitrequest
		.avalon_slave_writedata1     (i2c_master_0_avl_mm_writedata),                                 //  output,  width = 32,              .writedata
		.avalon_slave_read1          (i2c_master_0_avl_mm_read),                                      //  output,   width = 1,              .read
		.avalon_slave_readdata1      (i2c_master_0_avl_mm_readdata),                                  //   input,  width = 32,              .readdata
		.avalon_slave_readdatavalid1 (i2c_master_0_avl_mm_readdatavalid),                             //   input,   width = 1,              .readdatavalid
		.reset_sink_reset1           (i2c_master_0_avl_reset_reset)                                   //  output,   width = 1,   reset_sink1.reset
	);

	niosv_pd_avl_mst_sbc_0 avl_mst_sbc (
		.avalon_master_address        (avl_mst_sbc_avalon_master_address),       //  output,  width = 32,  avalon_master.address
		.avalon_master_waitrequest    (avl_mst_sbc_avalon_master_waitrequest),   //   input,   width = 1,               .waitrequest
		.avalon_master_write          (avl_mst_sbc_avalon_master_write),         //  output,   width = 1,               .write
		.avalon_master_writedata      (avl_mst_sbc_avalon_master_writedata),     //  output,  width = 32,               .writedata
		.avalon_master_read           (avl_mst_sbc_avalon_master_read),          //  output,   width = 1,               .read
		.avalon_master_readdata       (avl_mst_sbc_avalon_master_readdata),      //   input,  width = 32,               .readdata
		.avalon_master_readdatavalid  (avl_mst_sbc_avalon_master_readdatavalid), //   input,   width = 1,               .readdatavalid
		.clock_sink_clk               (clock_in_out_clk_clk),                    //   input,   width = 1,     clock_sink.clk
		.reset_sink_reset             (rst_controller_reset_out_reset),          //   input,   width = 1,     reset_sink.reset
		.avalon_master_address1       (avl_mst_sbc_address),                     //   input,  width = 32, avalon_master1.address
		.avalon_master_waitrequest1   (avl_mst_sbc_waitrequest),                 //  output,   width = 1,               .waitrequest
		.avalon_master_write1         (avl_mst_sbc_write),                       //   input,   width = 1,               .write
		.avalon_master_writedata1     (avl_mst_sbc_writedata),                   //   input,  width = 32,               .writedata
		.avalon_master_read1          (avl_mst_sbc_read),                        //   input,   width = 1,               .read
		.avalon_master_readdata1      (avl_mst_sbc_readdata),                    //  output,  width = 32,               .readdata
		.avalon_master_readdatavalid1 (avl_mst_sbc_readdatavalid),               //  output,   width = 1,               .readdatavalid
		.reset_sink_reset1            (avl_mst_sb_reset_reset)                   //  output,   width = 1,    reset_sink1.reset
	);

	niosv_pd_avl_spi_master_0 avl_spi_master_0 (
		.clock_sink_clk              (clock_in_out_clk_clk),                                          //   input,   width = 1,    clock_sink.clk
		.avalon_slave_address        (mm_interconnect_0_avl_spi_master_0_avalon_slave_address),       //   input,   width = 8,  avalon_slave.address
		.avalon_slave_chipselect     (mm_interconnect_0_avl_spi_master_0_avalon_slave_chipselect),    //   input,   width = 1,              .chipselect
		.avalon_slave_write          (mm_interconnect_0_avl_spi_master_0_avalon_slave_write),         //   input,   width = 1,              .write
		.avalon_slave_waitrequest    (mm_interconnect_0_avl_spi_master_0_avalon_slave_waitrequest),   //  output,   width = 1,              .waitrequest
		.avalon_slave_writedata      (mm_interconnect_0_avl_spi_master_0_avalon_slave_writedata),     //   input,  width = 32,              .writedata
		.avalon_slave_read           (mm_interconnect_0_avl_spi_master_0_avalon_slave_read),          //   input,   width = 1,              .read
		.avalon_slave_readdata       (mm_interconnect_0_avl_spi_master_0_avalon_slave_readdata),      //  output,  width = 32,              .readdata
		.avalon_slave_readdatavalid  (mm_interconnect_0_avl_spi_master_0_avalon_slave_readdatavalid), //  output,   width = 1,              .readdatavalid
		.reset_sink_reset            (rst_controller_reset_out_reset),                                //   input,   width = 1,    reset_sink.reset
		.avalon_slave_address1       (spi_master_0_avl_mm_address),                                   //  output,   width = 8, avalon_slave1.address
		.avalon_slave_chipselect1    (spi_master_0_avl_mm_chipselect),                                //  output,   width = 1,              .chipselect
		.avalon_slave_write1         (spi_master_0_avl_mm_write),                                     //  output,   width = 1,              .write
		.avalon_slave_waitrequest1   (spi_master_0_avl_mm_waitrequest),                               //   input,   width = 1,              .waitrequest
		.avalon_slave_writedata1     (spi_master_0_avl_mm_writedata),                                 //  output,  width = 32,              .writedata
		.avalon_slave_read1          (spi_master_0_avl_mm_read),                                      //  output,   width = 1,              .read
		.avalon_slave_readdata1      (spi_master_0_avl_mm_readdata),                                  //   input,  width = 32,              .readdata
		.avalon_slave_readdatavalid1 (spi_master_0_avl_mm_readdatavalid),                             //   input,   width = 1,              .readdatavalid
		.reset_sink_reset1           (spi_master_0_avl_reset_reset)                                   //  output,   width = 1,   reset_sink1.reset
	);

	niosv_pd_clock_in clock_in (
		.in_clk  (clk_clk),              //   input,  width = 1,  in_clk.clk
		.out_clk (clock_in_out_clk_clk)  //  output,  width = 1, out_clk.clk
	);

	niosv_pd_intel_onchip_memory_1 data_memory_1 (
		.clk        (clock_in_out_clk_clk),                          //   input,   width = 1,   clk1.clk
		.address    (mm_interconnect_0_data_memory_1_s1_address),    //   input,  width = 15,     s1.address
		.read       (mm_interconnect_0_data_memory_1_s1_read),       //   input,   width = 1,       .read
		.readdata   (mm_interconnect_0_data_memory_1_s1_readdata),   //  output,  width = 32,       .readdata
		.byteenable (mm_interconnect_0_data_memory_1_s1_byteenable), //   input,   width = 4,       .byteenable
		.write      (mm_interconnect_0_data_memory_1_s1_write),      //   input,   width = 1,       .write
		.writedata  (mm_interconnect_0_data_memory_1_s1_writedata),  //   input,  width = 32,       .writedata
		.reset      (rst_controller_reset_out_reset),                //   input,   width = 1, reset1.reset
		.reset_req  (rst_controller_reset_out_reset_req)             //   input,   width = 1,       .reset_req
	);

	niosv_pd_intel_mailbox_client_0 intel_mailbox_client_0 (
		.in_clk_clk         (clock_in_out_clk_clk),                                        //   input,   width = 1,   in_clk.clk
		.in_reset_reset     (rst_controller_001_reset_out_reset),                          //   input,   width = 1, in_reset.reset
		.avmm_address       (mm_interconnect_0_intel_mailbox_client_0_avmm_address),       //   input,   width = 4,     avmm.address
		.avmm_write         (mm_interconnect_0_intel_mailbox_client_0_avmm_write),         //   input,   width = 1,         .write
		.avmm_writedata     (mm_interconnect_0_intel_mailbox_client_0_avmm_writedata),     //   input,  width = 32,         .writedata
		.avmm_read          (mm_interconnect_0_intel_mailbox_client_0_avmm_read),          //   input,   width = 1,         .read
		.avmm_readdata      (mm_interconnect_0_intel_mailbox_client_0_avmm_readdata),      //  output,  width = 32,         .readdata
		.avmm_readdatavalid (mm_interconnect_0_intel_mailbox_client_0_avmm_readdatavalid), //  output,   width = 1,         .readdatavalid
		.avmm_waitrequest   (mm_interconnect_0_intel_mailbox_client_0_avmm_waitrequest),   //  output,   width = 1,         .waitrequest
		.irq_irq            ()                                                             //  output,   width = 1,      irq.irq
	);

	niosv_pd_jesd_12_chan_interface_0 jesd_12_chan_interface_0 (
		.address                  (mm_interconnect_0_jesd_12_chan_interface_0_avalon_slave_address),     //   input,  width = 10,  avalon_slave.address
		.chipselect               (mm_interconnect_0_jesd_12_chan_interface_0_avalon_slave_chipselect),  //   input,   width = 1,              .chipselect
		.read                     (mm_interconnect_0_jesd_12_chan_interface_0_avalon_slave_read),        //   input,   width = 1,              .read
		.readdata                 (mm_interconnect_0_jesd_12_chan_interface_0_avalon_slave_readdata),    //  output,  width = 32,              .readdata
		.waitrequest              (mm_interconnect_0_jesd_12_chan_interface_0_avalon_slave_waitrequest), //  output,   width = 1,              .waitrequest
		.write                    (mm_interconnect_0_jesd_12_chan_interface_0_avalon_slave_write),       //   input,   width = 1,              .write
		.writedata                (mm_interconnect_0_jesd_12_chan_interface_0_avalon_slave_writedata),   //   input,  width = 32,              .writedata
		.clk                      (clock_in_out_clk_clk),                                                //   input,   width = 1,    clock_sink.clk
		.reset                    (~rst_controller_reset_out_reset),                                     //   input,   width = 1,    reset_sink.reset_n
		.avalon_slave_address     (jesd_low_slave_address),                                              //  output,  width = 10, avalon_slave1.address
		.avalon_slave_chipselect  (jesd_low_slave_chipselect),                                           //  output,   width = 1,              .chipselect
		.avalon_slave_read        (jesd_low_slave_read),                                                 //  output,   width = 1,              .read
		.avalon_slave_readdata    (jesd_low_slave_readdata),                                             //   input,  width = 32,              .readdata
		.avalon_slave_waitrequest (jesd_low_slave_waitrequest),                                          //   input,   width = 1,              .waitrequest
		.avalon_slave_write       (jesd_low_slave_write),                                                //  output,   width = 1,              .write
		.avalon_slave_writedata   (jesd_low_slave_writedata),                                            //  output,  width = 32,              .writedata
		.reset_sink_reset_n       (jesd_low_slave_reset_reset_n)                                         //  output,   width = 1,   reset_sink1.reset_n
	);

	niosv_pd_jesd_12_chan_interface_1 jesd_12_chan_interface_1 (
		.address                  (mm_interconnect_0_jesd_12_chan_interface_1_avalon_slave_address),     //   input,  width = 10,  avalon_slave.address
		.chipselect               (mm_interconnect_0_jesd_12_chan_interface_1_avalon_slave_chipselect),  //   input,   width = 1,              .chipselect
		.read                     (mm_interconnect_0_jesd_12_chan_interface_1_avalon_slave_read),        //   input,   width = 1,              .read
		.readdata                 (mm_interconnect_0_jesd_12_chan_interface_1_avalon_slave_readdata),    //  output,  width = 32,              .readdata
		.waitrequest              (mm_interconnect_0_jesd_12_chan_interface_1_avalon_slave_waitrequest), //  output,   width = 1,              .waitrequest
		.write                    (mm_interconnect_0_jesd_12_chan_interface_1_avalon_slave_write),       //   input,   width = 1,              .write
		.writedata                (mm_interconnect_0_jesd_12_chan_interface_1_avalon_slave_writedata),   //   input,  width = 32,              .writedata
		.clk                      (clock_in_out_clk_clk),                                                //   input,   width = 1,    clock_sink.clk
		.reset                    (~rst_controller_reset_out_reset),                                     //   input,   width = 1,    reset_sink.reset_n
		.avalon_slave_address     (jesd_high_slave_address),                                             //  output,  width = 10, avalon_slave1.address
		.avalon_slave_chipselect  (jesd_high_slave_chipselect),                                          //  output,   width = 1,              .chipselect
		.avalon_slave_read        (jesd_high_slave_read),                                                //  output,   width = 1,              .read
		.avalon_slave_readdata    (jesd_high_slave_readdata),                                            //   input,  width = 32,              .readdata
		.avalon_slave_waitrequest (jesd_high_slave_waitrequest),                                         //   input,   width = 1,              .waitrequest
		.avalon_slave_write       (jesd_high_slave_write),                                               //  output,   width = 1,              .write
		.avalon_slave_writedata   (jesd_high_slave_writedata),                                           //  output,  width = 32,              .writedata
		.reset_sink_reset_n       (jesd_high_slave_reset_reset_n)                                        //  output,   width = 1,   reset_sink1.reset_n
	);

	niosv_pd_intel_lw_uart_0 pd_uart (
		.clk       (clock_in_out_clk_clk),                   //   input,   width = 1,                 clk.clk
		.reset_n   (~rst_controller_reset_out_reset),        //   input,   width = 1,               reset.reset_n
		.address   (mm_interconnect_0_pd_uart_s1_address),   //   input,   width = 3,                  s1.address
		.read      (mm_interconnect_0_pd_uart_s1_read),      //   input,   width = 1,                    .read
		.write     (mm_interconnect_0_pd_uart_s1_write),     //   input,   width = 1,                    .write
		.writedata (mm_interconnect_0_pd_uart_s1_writedata), //   input,  width = 16,                    .writedata
		.readdata  (mm_interconnect_0_pd_uart_s1_readdata),  //  output,  width = 16,                    .readdata
		.rxd       (pd_debug_uart_rxd),                      //   input,   width = 1, external_connection.rxd
		.txd       (pd_debug_uart_txd),                      //  output,   width = 1,                    .txd
		.irq       ()                                        //  output,   width = 1,                 irq.irq
	);

	niosv_pd_intel_onchip_memory_0 program_memory_0 (
		.clk        (clock_in_out_clk_clk),                             //   input,   width = 1,   clk1.clk
		.address    (mm_interconnect_0_program_memory_0_s1_address),    //   input,  width = 15,     s1.address
		.read       (mm_interconnect_0_program_memory_0_s1_read),       //   input,   width = 1,       .read
		.readdata   (mm_interconnect_0_program_memory_0_s1_readdata),   //  output,  width = 32,       .readdata
		.byteenable (mm_interconnect_0_program_memory_0_s1_byteenable), //   input,   width = 4,       .byteenable
		.write      (mm_interconnect_0_program_memory_0_s1_write),      //   input,   width = 1,       .write
		.writedata  (mm_interconnect_0_program_memory_0_s1_writedata),  //   input,  width = 32,       .writedata
		.reset      (rst_controller_reset_out_reset),                   //   input,   width = 1, reset1.reset
		.reset_req  (rst_controller_reset_out_reset_req)                //   input,   width = 1,       .reset_req
	);

	niosv_pd_reset_in reset_in (
		.clk         (clock_in_out_clk_clk),     //   input,  width = 1,       clk.clk
		.in_reset_n  (reset_reset_n),            //   input,  width = 1,  in_reset.reset_n
		.out_reset_n (reset_in_out_reset_reset)  //  output,  width = 1, out_reset.reset_n
	);

	niosv_pd_tectonics_ser_debug_0 tectonics_ser_debug_0 (
		.avalon_master_address        (tectonics_ser_debug_0_avalon_master_address),       //  output,  width = 32,  avalon_master.address
		.avalon_master_waitrequest    (tectonics_ser_debug_0_avalon_master_waitrequest),   //   input,   width = 1,               .waitrequest
		.avalon_master_write          (tectonics_ser_debug_0_avalon_master_write),         //  output,   width = 1,               .write
		.avalon_master_writedata      (tectonics_ser_debug_0_avalon_master_writedata),     //  output,  width = 32,               .writedata
		.avalon_master_read           (tectonics_ser_debug_0_avalon_master_read),          //  output,   width = 1,               .read
		.avalon_master_readdata       (tectonics_ser_debug_0_avalon_master_readdata),      //   input,  width = 32,               .readdata
		.avalon_master_readdatavalid  (tectonics_ser_debug_0_avalon_master_readdatavalid), //   input,   width = 1,               .readdatavalid
		.avalon_master_byteenable     (tectonics_ser_debug_0_avalon_master_byteenable),    //  output,   width = 4,               .byteenable
		.clock_sink_clk               (clock_in_out_clk_clk),                              //   input,   width = 1,     clock_sink.clk
		.reset_sink_reset             (rst_controller_reset_out_reset),                    //   input,   width = 1,     reset_sink.reset
		.avalon_master_address1       (ser_debug_master_address),                          //   input,  width = 32, avalon_master1.address
		.avalon_master_waitrequest1   (ser_debug_master_waitrequest),                      //  output,   width = 1,               .waitrequest
		.avalon_master_write1         (ser_debug_master_write),                            //   input,   width = 1,               .write
		.avalon_master_writedata1     (ser_debug_master_writedata),                        //   input,  width = 32,               .writedata
		.avalon_master_read1          (ser_debug_master_read),                             //   input,   width = 1,               .read
		.avalon_master_readdata1      (ser_debug_master_readdata),                         //  output,  width = 32,               .readdata
		.avalon_master_readdatavalid1 (ser_debug_master_readdatavalid),                    //  output,   width = 1,               .readdatavalid
		.avalon_master_byteenable1    (ser_debug_master_byteenable),                       //   input,   width = 4,               .byteenable
		.reset_sink_reset1            (ser_debug_master_reset_reset)                       //  output,   width = 1,    reset_sink1.reset
	);

	niosv_pd_timer_0 timer_0 (
		.clk           (clock_in_out_clk_clk),                    //   input,   width = 1,           clk.clk
		.reset_n       (~rst_controller_reset_out_reset),         //   input,   width = 1,         reset.reset_n
		.address       (mm_interconnect_0_timer_0_s1_address),    //   input,   width = 3,            s1.address
		.writedata     (mm_interconnect_0_timer_0_s1_writedata),  //   input,  width = 16,              .writedata
		.readdata      (mm_interconnect_0_timer_0_s1_readdata),   //  output,  width = 16,              .readdata
		.chipselect    (mm_interconnect_0_timer_0_s1_chipselect), //   input,   width = 1,              .chipselect
		.write_n       (~mm_interconnect_0_timer_0_s1_write),     //   input,   width = 1,              .write_n
		.irq           (),                                        //  output,   width = 1,           irq.irq
		.timeout_pulse ()                                         //  output,   width = 1, external_port.export
	);

	niosv_pd_altera_mm_interconnect_1920_3szymzi mm_interconnect_0 (
		.tectonics_ser_debug_0_avalon_master_address                  (tectonics_ser_debug_0_avalon_master_address),                         //   input,  width = 32,                    tectonics_ser_debug_0_avalon_master.address
		.tectonics_ser_debug_0_avalon_master_waitrequest              (tectonics_ser_debug_0_avalon_master_waitrequest),                     //  output,   width = 1,                                                       .waitrequest
		.tectonics_ser_debug_0_avalon_master_byteenable               (tectonics_ser_debug_0_avalon_master_byteenable),                      //   input,   width = 4,                                                       .byteenable
		.tectonics_ser_debug_0_avalon_master_read                     (tectonics_ser_debug_0_avalon_master_read),                            //   input,   width = 1,                                                       .read
		.tectonics_ser_debug_0_avalon_master_readdata                 (tectonics_ser_debug_0_avalon_master_readdata),                        //  output,  width = 32,                                                       .readdata
		.tectonics_ser_debug_0_avalon_master_readdatavalid            (tectonics_ser_debug_0_avalon_master_readdatavalid),                   //  output,   width = 1,                                                       .readdatavalid
		.tectonics_ser_debug_0_avalon_master_write                    (tectonics_ser_debug_0_avalon_master_write),                           //   input,   width = 1,                                                       .write
		.tectonics_ser_debug_0_avalon_master_writedata                (tectonics_ser_debug_0_avalon_master_writedata),                       //   input,  width = 32,                                                       .writedata
		.avl_mst_sbc_avalon_master_address                            (avl_mst_sbc_avalon_master_address),                                   //   input,  width = 32,                              avl_mst_sbc_avalon_master.address
		.avl_mst_sbc_avalon_master_waitrequest                        (avl_mst_sbc_avalon_master_waitrequest),                               //  output,   width = 1,                                                       .waitrequest
		.avl_mst_sbc_avalon_master_read                               (avl_mst_sbc_avalon_master_read),                                      //   input,   width = 1,                                                       .read
		.avl_mst_sbc_avalon_master_readdata                           (avl_mst_sbc_avalon_master_readdata),                                  //  output,  width = 32,                                                       .readdata
		.avl_mst_sbc_avalon_master_readdatavalid                      (avl_mst_sbc_avalon_master_readdatavalid),                             //  output,   width = 1,                                                       .readdatavalid
		.avl_mst_sbc_avalon_master_write                              (avl_mst_sbc_avalon_master_write),                                     //   input,   width = 1,                                                       .write
		.avl_mst_sbc_avalon_master_writedata                          (avl_mst_sbc_avalon_master_writedata),                                 //   input,  width = 32,                                                       .writedata
		.jesd_12_chan_interface_1_avalon_slave_address                (mm_interconnect_0_jesd_12_chan_interface_1_avalon_slave_address),     //  output,  width = 10,                  jesd_12_chan_interface_1_avalon_slave.address
		.jesd_12_chan_interface_1_avalon_slave_write                  (mm_interconnect_0_jesd_12_chan_interface_1_avalon_slave_write),       //  output,   width = 1,                                                       .write
		.jesd_12_chan_interface_1_avalon_slave_read                   (mm_interconnect_0_jesd_12_chan_interface_1_avalon_slave_read),        //  output,   width = 1,                                                       .read
		.jesd_12_chan_interface_1_avalon_slave_readdata               (mm_interconnect_0_jesd_12_chan_interface_1_avalon_slave_readdata),    //   input,  width = 32,                                                       .readdata
		.jesd_12_chan_interface_1_avalon_slave_writedata              (mm_interconnect_0_jesd_12_chan_interface_1_avalon_slave_writedata),   //  output,  width = 32,                                                       .writedata
		.jesd_12_chan_interface_1_avalon_slave_waitrequest            (mm_interconnect_0_jesd_12_chan_interface_1_avalon_slave_waitrequest), //   input,   width = 1,                                                       .waitrequest
		.jesd_12_chan_interface_1_avalon_slave_chipselect             (mm_interconnect_0_jesd_12_chan_interface_1_avalon_slave_chipselect),  //  output,   width = 1,                                                       .chipselect
		.jesd_12_chan_interface_0_avalon_slave_address                (mm_interconnect_0_jesd_12_chan_interface_0_avalon_slave_address),     //  output,  width = 10,                  jesd_12_chan_interface_0_avalon_slave.address
		.jesd_12_chan_interface_0_avalon_slave_write                  (mm_interconnect_0_jesd_12_chan_interface_0_avalon_slave_write),       //  output,   width = 1,                                                       .write
		.jesd_12_chan_interface_0_avalon_slave_read                   (mm_interconnect_0_jesd_12_chan_interface_0_avalon_slave_read),        //  output,   width = 1,                                                       .read
		.jesd_12_chan_interface_0_avalon_slave_readdata               (mm_interconnect_0_jesd_12_chan_interface_0_avalon_slave_readdata),    //   input,  width = 32,                                                       .readdata
		.jesd_12_chan_interface_0_avalon_slave_writedata              (mm_interconnect_0_jesd_12_chan_interface_0_avalon_slave_writedata),   //  output,  width = 32,                                                       .writedata
		.jesd_12_chan_interface_0_avalon_slave_waitrequest            (mm_interconnect_0_jesd_12_chan_interface_0_avalon_slave_waitrequest), //   input,   width = 1,                                                       .waitrequest
		.jesd_12_chan_interface_0_avalon_slave_chipselect             (mm_interconnect_0_jesd_12_chan_interface_0_avalon_slave_chipselect),  //  output,   width = 1,                                                       .chipselect
		.avalon_spi_slave_0_avalon_slave_address                      (mm_interconnect_0_avalon_spi_slave_0_avalon_slave_address),           //  output,  width = 15,                        avalon_spi_slave_0_avalon_slave.address
		.avalon_spi_slave_0_avalon_slave_write                        (mm_interconnect_0_avalon_spi_slave_0_avalon_slave_write),             //  output,   width = 1,                                                       .write
		.avalon_spi_slave_0_avalon_slave_read                         (mm_interconnect_0_avalon_spi_slave_0_avalon_slave_read),              //  output,   width = 1,                                                       .read
		.avalon_spi_slave_0_avalon_slave_readdata                     (mm_interconnect_0_avalon_spi_slave_0_avalon_slave_readdata),          //   input,  width = 32,                                                       .readdata
		.avalon_spi_slave_0_avalon_slave_writedata                    (mm_interconnect_0_avalon_spi_slave_0_avalon_slave_writedata),         //  output,  width = 32,                                                       .writedata
		.avalon_spi_slave_0_avalon_slave_readdatavalid                (mm_interconnect_0_avalon_spi_slave_0_avalon_slave_readdatavalid),     //   input,   width = 1,                                                       .readdatavalid
		.avalon_spi_slave_0_avalon_slave_waitrequest                  (mm_interconnect_0_avalon_spi_slave_0_avalon_slave_waitrequest),       //   input,   width = 1,                                                       .waitrequest
		.avalon_spi_slave_0_avalon_slave_chipselect                   (mm_interconnect_0_avalon_spi_slave_0_avalon_slave_chipselect),        //  output,   width = 1,                                                       .chipselect
		.avl_spi_master_0_avalon_slave_address                        (mm_interconnect_0_avl_spi_master_0_avalon_slave_address),             //  output,   width = 8,                          avl_spi_master_0_avalon_slave.address
		.avl_spi_master_0_avalon_slave_write                          (mm_interconnect_0_avl_spi_master_0_avalon_slave_write),               //  output,   width = 1,                                                       .write
		.avl_spi_master_0_avalon_slave_read                           (mm_interconnect_0_avl_spi_master_0_avalon_slave_read),                //  output,   width = 1,                                                       .read
		.avl_spi_master_0_avalon_slave_readdata                       (mm_interconnect_0_avl_spi_master_0_avalon_slave_readdata),            //   input,  width = 32,                                                       .readdata
		.avl_spi_master_0_avalon_slave_writedata                      (mm_interconnect_0_avl_spi_master_0_avalon_slave_writedata),           //  output,  width = 32,                                                       .writedata
		.avl_spi_master_0_avalon_slave_readdatavalid                  (mm_interconnect_0_avl_spi_master_0_avalon_slave_readdatavalid),       //   input,   width = 1,                                                       .readdatavalid
		.avl_spi_master_0_avalon_slave_waitrequest                    (mm_interconnect_0_avl_spi_master_0_avalon_slave_waitrequest),         //   input,   width = 1,                                                       .waitrequest
		.avl_spi_master_0_avalon_slave_chipselect                     (mm_interconnect_0_avl_spi_master_0_avalon_slave_chipselect),          //  output,   width = 1,                                                       .chipselect
		.avl_i2c_master_0_avalon_slave_address                        (mm_interconnect_0_avl_i2c_master_0_avalon_slave_address),             //  output,   width = 8,                          avl_i2c_master_0_avalon_slave.address
		.avl_i2c_master_0_avalon_slave_write                          (mm_interconnect_0_avl_i2c_master_0_avalon_slave_write),               //  output,   width = 1,                                                       .write
		.avl_i2c_master_0_avalon_slave_read                           (mm_interconnect_0_avl_i2c_master_0_avalon_slave_read),                //  output,   width = 1,                                                       .read
		.avl_i2c_master_0_avalon_slave_readdata                       (mm_interconnect_0_avl_i2c_master_0_avalon_slave_readdata),            //   input,  width = 32,                                                       .readdata
		.avl_i2c_master_0_avalon_slave_writedata                      (mm_interconnect_0_avl_i2c_master_0_avalon_slave_writedata),           //  output,  width = 32,                                                       .writedata
		.avl_i2c_master_0_avalon_slave_readdatavalid                  (mm_interconnect_0_avl_i2c_master_0_avalon_slave_readdatavalid),       //   input,   width = 1,                                                       .readdatavalid
		.avl_i2c_master_0_avalon_slave_waitrequest                    (mm_interconnect_0_avl_i2c_master_0_avalon_slave_waitrequest),         //   input,   width = 1,                                                       .waitrequest
		.avl_i2c_master_0_avalon_slave_chipselect                     (mm_interconnect_0_avl_i2c_master_0_avalon_slave_chipselect),          //  output,   width = 1,                                                       .chipselect
		.intel_mailbox_client_0_avmm_address                          (mm_interconnect_0_intel_mailbox_client_0_avmm_address),               //  output,   width = 4,                            intel_mailbox_client_0_avmm.address
		.intel_mailbox_client_0_avmm_write                            (mm_interconnect_0_intel_mailbox_client_0_avmm_write),                 //  output,   width = 1,                                                       .write
		.intel_mailbox_client_0_avmm_read                             (mm_interconnect_0_intel_mailbox_client_0_avmm_read),                  //  output,   width = 1,                                                       .read
		.intel_mailbox_client_0_avmm_readdata                         (mm_interconnect_0_intel_mailbox_client_0_avmm_readdata),              //   input,  width = 32,                                                       .readdata
		.intel_mailbox_client_0_avmm_writedata                        (mm_interconnect_0_intel_mailbox_client_0_avmm_writedata),             //  output,  width = 32,                                                       .writedata
		.intel_mailbox_client_0_avmm_readdatavalid                    (mm_interconnect_0_intel_mailbox_client_0_avmm_readdatavalid),         //   input,   width = 1,                                                       .readdatavalid
		.intel_mailbox_client_0_avmm_waitrequest                      (mm_interconnect_0_intel_mailbox_client_0_avmm_waitrequest),           //   input,   width = 1,                                                       .waitrequest
		.pd_uart_s1_address                                           (mm_interconnect_0_pd_uart_s1_address),                                //  output,   width = 3,                                             pd_uart_s1.address
		.pd_uart_s1_write                                             (mm_interconnect_0_pd_uart_s1_write),                                  //  output,   width = 1,                                                       .write
		.pd_uart_s1_read                                              (mm_interconnect_0_pd_uart_s1_read),                                   //  output,   width = 1,                                                       .read
		.pd_uart_s1_readdata                                          (mm_interconnect_0_pd_uart_s1_readdata),                               //   input,  width = 16,                                                       .readdata
		.pd_uart_s1_writedata                                         (mm_interconnect_0_pd_uart_s1_writedata),                              //  output,  width = 16,                                                       .writedata
		.timer_0_s1_address                                           (mm_interconnect_0_timer_0_s1_address),                                //  output,   width = 3,                                             timer_0_s1.address
		.timer_0_s1_write                                             (mm_interconnect_0_timer_0_s1_write),                                  //  output,   width = 1,                                                       .write
		.timer_0_s1_readdata                                          (mm_interconnect_0_timer_0_s1_readdata),                               //   input,  width = 16,                                                       .readdata
		.timer_0_s1_writedata                                         (mm_interconnect_0_timer_0_s1_writedata),                              //  output,  width = 16,                                                       .writedata
		.timer_0_s1_chipselect                                        (mm_interconnect_0_timer_0_s1_chipselect),                             //  output,   width = 1,                                                       .chipselect
		.data_memory_1_s1_address                                     (mm_interconnect_0_data_memory_1_s1_address),                          //  output,  width = 15,                                       data_memory_1_s1.address
		.data_memory_1_s1_write                                       (mm_interconnect_0_data_memory_1_s1_write),                            //  output,   width = 1,                                                       .write
		.data_memory_1_s1_read                                        (mm_interconnect_0_data_memory_1_s1_read),                             //  output,   width = 1,                                                       .read
		.data_memory_1_s1_readdata                                    (mm_interconnect_0_data_memory_1_s1_readdata),                         //   input,  width = 32,                                                       .readdata
		.data_memory_1_s1_writedata                                   (mm_interconnect_0_data_memory_1_s1_writedata),                        //  output,  width = 32,                                                       .writedata
		.data_memory_1_s1_byteenable                                  (mm_interconnect_0_data_memory_1_s1_byteenable),                       //  output,   width = 4,                                                       .byteenable
		.program_memory_0_s1_address                                  (mm_interconnect_0_program_memory_0_s1_address),                       //  output,  width = 15,                                    program_memory_0_s1.address
		.program_memory_0_s1_write                                    (mm_interconnect_0_program_memory_0_s1_write),                         //  output,   width = 1,                                                       .write
		.program_memory_0_s1_read                                     (mm_interconnect_0_program_memory_0_s1_read),                          //  output,   width = 1,                                                       .read
		.program_memory_0_s1_readdata                                 (mm_interconnect_0_program_memory_0_s1_readdata),                      //   input,  width = 32,                                                       .readdata
		.program_memory_0_s1_writedata                                (mm_interconnect_0_program_memory_0_s1_writedata),                     //  output,  width = 32,                                                       .writedata
		.program_memory_0_s1_byteenable                               (mm_interconnect_0_program_memory_0_s1_byteenable),                    //  output,   width = 4,                                                       .byteenable
		.tectonics_ser_debug_0_reset_sink_reset_bridge_in_reset_reset (rst_controller_001_reset_out_reset),                                  //   input,   width = 1, tectonics_ser_debug_0_reset_sink_reset_bridge_in_reset.reset
		.intel_mailbox_client_0_in_reset_reset_bridge_in_reset_reset  (rst_controller_001_reset_out_reset),                                  //   input,   width = 1,  intel_mailbox_client_0_in_reset_reset_bridge_in_reset.reset
		.clock_in_out_clk_clk                                         (clock_in_out_clk_clk)                                                 //   input,   width = 1,                                       clock_in_out_clk.clk
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (1),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (~reset_in_out_reset_reset),          //   input,  width = 1, reset_in0.reset
		.clk            (clock_in_out_clk_clk),               //   input,  width = 1,       clk.clk
		.reset_out      (rst_controller_reset_out_reset),     //  output,  width = 1, reset_out.reset
		.reset_req      (rst_controller_reset_out_reset_req), //  output,  width = 1,          .reset_req
		.reset_req_in0  (1'b0),                               // (terminated),                       
		.reset_in1      (1'b0),                               // (terminated),                       
		.reset_req_in1  (1'b0),                               // (terminated),                       
		.reset_in2      (1'b0),                               // (terminated),                       
		.reset_req_in2  (1'b0),                               // (terminated),                       
		.reset_in3      (1'b0),                               // (terminated),                       
		.reset_req_in3  (1'b0),                               // (terminated),                       
		.reset_in4      (1'b0),                               // (terminated),                       
		.reset_req_in4  (1'b0),                               // (terminated),                       
		.reset_in5      (1'b0),                               // (terminated),                       
		.reset_req_in5  (1'b0),                               // (terminated),                       
		.reset_in6      (1'b0),                               // (terminated),                       
		.reset_req_in6  (1'b0),                               // (terminated),                       
		.reset_in7      (1'b0),                               // (terminated),                       
		.reset_req_in7  (1'b0),                               // (terminated),                       
		.reset_in8      (1'b0),                               // (terminated),                       
		.reset_req_in8  (1'b0),                               // (terminated),                       
		.reset_in9      (1'b0),                               // (terminated),                       
		.reset_req_in9  (1'b0),                               // (terminated),                       
		.reset_in10     (1'b0),                               // (terminated),                       
		.reset_req_in10 (1'b0),                               // (terminated),                       
		.reset_in11     (1'b0),                               // (terminated),                       
		.reset_req_in11 (1'b0),                               // (terminated),                       
		.reset_in12     (1'b0),                               // (terminated),                       
		.reset_req_in12 (1'b0),                               // (terminated),                       
		.reset_in13     (1'b0),                               // (terminated),                       
		.reset_req_in13 (1'b0),                               // (terminated),                       
		.reset_in14     (1'b0),                               // (terminated),                       
		.reset_req_in14 (1'b0),                               // (terminated),                       
		.reset_in15     (1'b0),                               // (terminated),                       
		.reset_req_in15 (1'b0)                                // (terminated),                       
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("both"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller_001 (
		.reset_in0      (~reset_in_out_reset_reset),          //   input,  width = 1, reset_in0.reset
		.clk            (clock_in_out_clk_clk),               //   input,  width = 1,       clk.clk
		.reset_out      (rst_controller_001_reset_out_reset), //  output,  width = 1, reset_out.reset
		.reset_req      (),                                   // (terminated),                       
		.reset_req_in0  (1'b0),                               // (terminated),                       
		.reset_in1      (1'b0),                               // (terminated),                       
		.reset_req_in1  (1'b0),                               // (terminated),                       
		.reset_in2      (1'b0),                               // (terminated),                       
		.reset_req_in2  (1'b0),                               // (terminated),                       
		.reset_in3      (1'b0),                               // (terminated),                       
		.reset_req_in3  (1'b0),                               // (terminated),                       
		.reset_in4      (1'b0),                               // (terminated),                       
		.reset_req_in4  (1'b0),                               // (terminated),                       
		.reset_in5      (1'b0),                               // (terminated),                       
		.reset_req_in5  (1'b0),                               // (terminated),                       
		.reset_in6      (1'b0),                               // (terminated),                       
		.reset_req_in6  (1'b0),                               // (terminated),                       
		.reset_in7      (1'b0),                               // (terminated),                       
		.reset_req_in7  (1'b0),                               // (terminated),                       
		.reset_in8      (1'b0),                               // (terminated),                       
		.reset_req_in8  (1'b0),                               // (terminated),                       
		.reset_in9      (1'b0),                               // (terminated),                       
		.reset_req_in9  (1'b0),                               // (terminated),                       
		.reset_in10     (1'b0),                               // (terminated),                       
		.reset_req_in10 (1'b0),                               // (terminated),                       
		.reset_in11     (1'b0),                               // (terminated),                       
		.reset_req_in11 (1'b0),                               // (terminated),                       
		.reset_in12     (1'b0),                               // (terminated),                       
		.reset_req_in12 (1'b0),                               // (terminated),                       
		.reset_in13     (1'b0),                               // (terminated),                       
		.reset_req_in13 (1'b0),                               // (terminated),                       
		.reset_in14     (1'b0),                               // (terminated),                       
		.reset_req_in14 (1'b0),                               // (terminated),                       
		.reset_in15     (1'b0),                               // (terminated),                       
		.reset_req_in15 (1'b0)                                // (terminated),                       
	);

endmodule
